### ISSUE TITLE
NEW NAME FOR [NAPKIN INTERACTIVE]

### ISSUE THREAD

**Issue by AndreasAtakan** [NapkinGIS/Napkin-Globe#12]
Find a new and better name for Napkin Interactive, that better reflects the use-case that Napkin Interactive covers (being a meeting point for all map-data, from both Napkin and outside sources).

Alternatives:
- Napkin Viewer
- Napkin Presenter
- Napkin Insight
- Napkin Globe
- ...

**Comment by janpardy** [comment]
Napkin Oogler
Napkin View
Napkin Overview
Napkin Look
Napkin See
Napkin Bird's-eye

**Comment by AndreasAtakan** [comment]
Sort of landed on Napkin-Globe
